INSERT INTO burgers (name) VALUES ('Do Brussel Burger (comes with Brussels sprouts)');
INSERT INTO burgers (name) VALUES ('Burger a la Mode (comes with ice cream, not on top)');
INSERT INTO burgers (name) VALUES ('Ruta-Bag-A Burger');
INSERT INTO burgers (name) VALUES ('Romanes of the Day Burger');
INSERT INTO burgers (name) VALUES ('Its Only Sourdough Burger (But I Like It)');
INSERT INTO burgers (name) VALUES ('50 Ways to Leave Your Guava Burger');
INSERT INTO burgers (name) VALUES ('Summer Thyme Burger');
INSERT INTO burgers (name) VALUES ('Peas and Thank You Burger');
INSERT INTO burgers (name) VALUES ('I Am Mad About Saffron (made with no saffron)');
INSERT INTO burgers (name) VALUES ('Yes I Cayenne Burger ');
INSERT INTO burgers (name) VALUES ('Onion Burger - Grilled....To Death!');
INSERT INTO burgers (name) VALUES ('Sub-Conscious Burger (on a sub roll)');
INSERT INTO burgers (name) VALUES ('Tunami');
INSERT INTO burgers (name) VALUES ('Sweet Home Avocado Burger');
INSERT INTO burgers (name) VALUES ('I Mint to Do That Burger (comes with mint relish)');
INSERT INTO burgers (name) VALUES ('Bean Spirit (comes with beans)');
INSERT INTO burgers (name) VALUES ('Sharp Cheddar Dressed Man Burger (comes with sharp cheddar)');
INSERT INTO burgers (name) VALUES ('The Troy Oinkman Burger (served with bacon)');
INSERT INTO burgers (name) VALUES ('Is This Your Chard Burger');
INSERT INTO burgers (name) VALUES ('One Fish, Two Fish, Red Fish Hamburger');